/* eslint-disable import/named */
/* eslint-disable @typescript-eslint/ban-ts-ignore */
import * as React from 'react';
import {
  IconBot,
  IconBotFlows,
  IconModule,
  IconModuleLibrary,
  IconModuleTick,
  IconAPI,
  IconCMS,
  IconCommand,
  IconDeploy,
  IconEnvironments,
  IconNLU,
  IconData,
  IconOrganism,
  IconSingle,
  IconChartGraph,
  IconChartPie,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowDownRounded,
  IconArrowLeftRounded,
  IconArrowRightRounded,
  IconArrowUpRounded,
  IconCalendar,
  IconCalendarAdd,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronDownFilled,
  IconChevronLeftFilled,
  IconChevronRightFilled,
  IconChevronUpFilled,
  IconChevronDownRounded,
  IconChevronLeftRounded,
  IconChevronRightRounded,
  IconChevronUpRounded,
  IconClose,
  IconCloseRounded,
  IconDragHorizontal,
  IconDragVertical,
  IconDropDown,
  IconDropUp,
  IconEyeClose,
  IconEyeOpen,
  IconJumpNext,
  IconJumpPrevious,
  IconPlus,
  IconPlusRounded,
  IconTickDouble,
  IconTickRounded,
  IconTickSingle,
  IconWarningRounded,
  IconWarningTriangle,
  IconBell,
  IconClock,
  IconDownload,
  IconDrag,
  IconFilter,
  IconForward,
  IconGear,
  IconInfo,
  IconLock,
  IconLogout,
  IconLoop,
  IconMixer,
  IconRefresh,
  IconReply,
  IconSearch,
  IconTrash,
  IconUnlabel,
  IconUpload,
} from '../../../../aksara-icons';

interface IconMap {
  name: string;
  children: React.ReactNode;
}

type IconMapObject = Record<string, IconMap[]>;

const aksaraIconMaps: IconMapObject = {
  ai: [
    { name: 'IconBot', children: <IconBot /> },
    { name: 'IconBotFlows', children: <IconBotFlows /> },
    { name: 'IconModule', children: <IconModule /> },
    { name: 'IconModuleLibrary', children: <IconModuleLibrary /> },
    { name: 'IconModuleTick', children: <IconModuleTick /> },
    { name: 'IconAPI', children: <IconAPI /> },
    { name: 'IconCMS', children: <IconCMS /> },
    { name: 'IconCommand', children: <IconCommand /> },
    { name: 'IconDeploy', children: <IconDeploy /> },
    { name: 'IconEnvironments', children: <IconEnvironments /> },
    { name: 'IconNLU', children: <IconNLU /> },
  ],
  atoms: [
    { name: 'IconData', children: <IconData /> },
    { name: 'IconOrganism', children: <IconOrganism /> },
    { name: 'IconSingle', children: <IconSingle /> },
  ],
  basic: [
    { name: 'IconArrowDown', children: <IconArrowDown /> },
    { name: 'IconArrowLeft', children: <IconArrowLeft /> },
    { name: 'IconArrowRight', children: <IconArrowRight /> },
    { name: 'IconArrowUp', children: <IconArrowUp /> },
    { name: 'IconArrowDownRounded', children: <IconArrowDownRounded /> },
    { name: 'IconArrowLeftRounded', children: <IconArrowLeftRounded /> },
    { name: 'IconArrowRightRounded', children: <IconArrowRightRounded /> },
    { name: 'IconArrowUpRounded', children: <IconArrowUpRounded /> },
    { name: 'IconCalendar', children: <IconCalendar /> },
    { name: 'IconCalendarAdd', children: <IconCalendarAdd /> },
    { name: 'IconChevronDown', children: <IconChevronDown /> },
    { name: 'IconChevronLeft', children: <IconChevronLeft /> },
    { name: 'IconChevronRight', children: <IconChevronRight /> },
    { name: 'IconChevronUp', children: <IconChevronUp /> },
    { name: 'IconChevronDownFilled', children: <IconChevronDownFilled /> },
    { name: 'IconChevronLeftFilled', children: <IconChevronLeftFilled /> },
    { name: 'IconChevronRightFilled', children: <IconChevronRightFilled /> },
    { name: 'IconChevronUpFilled', children: <IconChevronUpFilled /> },
    { name: 'IconChevronDownRounded', children: <IconChevronDownRounded /> },
    { name: 'IconChevronLeftRounded', children: <IconChevronLeftRounded /> },
    { name: 'IconChevronRightRounded', children: <IconChevronRightRounded /> },
    { name: 'IconChevronUpRounded', children: <IconChevronUpRounded /> },
    { name: 'IconClose', children: <IconClose /> },
    { name: 'IconCloseRounded', children: <IconCloseRounded /> },
    { name: 'IconDragHorizontal', children: <IconDragHorizontal /> },
    { name: 'IconDragVertical', children: <IconDragVertical /> },
    { name: 'IconDropDown', children: <IconDropDown /> },
    { name: 'IconDropUp', children: <IconDropUp /> },
    { name: 'IconEyeClose', children: <IconEyeClose /> },
    { name: 'IconEyeOpen', children: <IconEyeOpen /> },
    { name: 'IconJumpNext', children: <IconJumpNext /> },
    { name: 'IconJumpPrevious', children: <IconJumpPrevious /> },
    { name: 'IconPlus', children: <IconPlus /> },
    { name: 'IconPlusRounded', children: <IconPlusRounded /> },
    { name: 'IconTickDouble', children: <IconTickDouble /> },
    { name: 'IconTickRounded', children: <IconTickRounded /> },
    { name: 'IconTickSingle', children: <IconTickSingle /> },
    { name: 'IconWarningRounded', children: <IconWarningRounded /> },
    { name: 'IconWarningTriangle', children: <IconWarningTriangle /> },
    { name: 'IconBell', children: <IconBell /> },
    { name: 'IconClock', children: <IconClock /> },
    { name: 'IconDownload', children: <IconDownload /> },
    { name: 'IconDrag', children: <IconDrag /> },
    { name: 'IconFilter', children: <IconFilter /> },
    { name: 'IconForward', children: <IconForward /> },
    { name: 'IconGear', children: <IconGear /> },
    { name: 'IconInfo', children: <IconInfo /> },
    { name: 'IconLock', children: <IconLock /> },
    { name: 'IconLogout', children: <IconLogout /> },
    { name: 'IconLoop', children: <IconLoop /> },
    { name: 'IconMixer', children: <IconMixer /> },
    { name: 'IconRefresh', children: <IconRefresh /> },
    { name: 'IconReply', children: <IconReply /> },
    { name: 'IconSearch', children: <IconSearch /> },
    { name: 'IconTrash', children: <IconTrash /> },
    { name: 'IconUnlabel', children: <IconUnlabel /> },
    { name: 'IconUpload', children: <IconUpload /> },
  ],
  chart: [
    { name: 'IconChartGraph', children: <IconChartGraph /> },
    { name: 'IconChartPie', children: <IconChartPie /> },
  ],
};

export default aksaraIconMaps;
