import * as React from 'react';

import {
  IconAPI,
  IconArrowDown,
  IconArrowDownRounded,
  IconArrowLeft,
  IconArrowLeftRounded,
  IconArrowRight,
  IconArrowRightRounded,
  IconArrowUp,
  IconArrowUpRounded,
  IconAudience,
  IconAudio,
  IconAugmentedReality,
  IconBehance,
  IconBell,
  IconBot,
  IconBot1,
  IconBot2,
  IconBotFlows,
  IconBrain,
  IconBrainSimulation,
  IconBriefcase,
  IconBubble,
  IconBubble2,
  IconBubble3,
  IconBubble4,
  IconBubble5,
  IconBubble6,
  IconBubble7,
  IconBubbleCheck,
  IconBubbleClose,
  IconBubbleEdit,
  IconBubbleLove,
  IconBubblePlus,
  IconBubbleTick,
  IconButton,
  IconCalendar,
  IconCalendarAdd,
  IconCamera,
  IconCampaign,
  IconCarousel,
  IconCarouselDynamic,
  IconCarouselImage,
  IconCartAdd,
  IconChartGraph,
  IconChartPie,
  IconChevronDown,
  IconChevronDownFilled,
  IconChevronDownRounded,
  IconChevronLeft,
  IconChevronLeftFilled,
  IconChevronLeftRounded,
  IconChevronRight,
  IconChevronRightFilled,
  IconChevronRightRounded,
  IconChevronUp,
  IconChevronUpFilled,
  IconChevronUpRounded,
  IconCircle,
  IconClient,
  IconClock,
  IconClose,
  IconCloseRounded,
  IconCloudUpload,
  IconCMS,
  IconCollaboration,
  IconCommand,
  IconConversation,
  IconConversation1,
  IconConversation2,
  IconConversation3,
  IconConversation4,
  IconCopy,
  IconCrystalLamp,
  IconData,
  IconDeploy,
  IconDesign,
  IconDiamond,
  IconDictionary,
  IconDoc,
  IconDocAdd,
  IconDownload,
  IconDrag,
  IconDragHorizontal,
  IconDragVertical,
  IconDribble,
  IconDropDown,
  IconDropdown,
  IconDropLeft,
  IconDropRight,
  IconDropUp,
  IconEmoji,
  IconEntities,
  IconEnvironments,
  IconEyeClose,
  IconEyeOpen,
  IconEyeRecognition,
  IconEyeUnvisible,
  IconFacebook,
  IconFacebookMessenger,
  IconFAQ,
  IconFilter,
  IconFingerprint,
  IconFlag,
  IconFlowerGrid,
  IconForward,
  IconGear,
  IconGithub,
  IconGrid,
  IconGuides,
  IconHamburger,
  IconHistory,
  IconHumanoid,
  IconHumanoid2,
  IconHumanoid3,
  IconIdeaBrain,
  IconImage,
  IconImageAdd,
  IconImageMap,
  IconInfo,
  IconInstagram,
  IconIntelligence,
  IconJumpNext,
  IconJumpPrevious,
  IconKebab,
  IconKebabHorizontal,
  IconKebabRounded,
  IconLine,
  IconLink,
  IconLinkedin,
  IconLinkHorizontal,
  IconLinkVertical,
  IconList,
  IconLocator,
  IconLock,
  IconLogout,
  IconLoop,
  IconMarker,
  IconMenu,
  IconMenuFilter,
  IconMessage,
  IconMessageBot,
  IconMessageTemplate,
  IconMinus,
  IconMinusRound,
  IconMixer,
  IconModule,
  IconModuleLibrary,
  IconModuleTick,
  IconNeutral1,
  IconNeutral2,
  IconNeutral3,
  IconNLU,
  IconNLUs,
  IconNLUTrait,
  IconOrganism,
  IconOutgoing,
  IconOutgoingFill,
  IconPage,
  IconPaperPlane,
  IconPen,
  IconPersistentMenu,
  IconPhrase,
  IconPlug,
  IconPlus,
  IconPlusRounded,
  IconQuickForward,
  IconQuickReply,
  IconRefresh,
  IconReply,
  IconRobotic,
  IconSave,
  IconSearch,
  IconSend,
  IconShare,
  IconShutdown,
  IconSingle,
  IconSlack,
  IconSlinder,
  IconSound,
  IconSquare,
  IconStar,
  IconSticker,
  IconStore,
  IconTemplate,
  IconTemplateMenu,
  IconTextArea,
  IconTextBox,
  IconTextData,
  IconTextList,
  IconTickDouble,
  IconTickRounded,
  IconTickSingle,
  IconToggle,
  IconTooltipBottom,
  IconTooltipLeft,
  IconTooltipLove,
  IconTooltipRight,
  IconTooltipTop,
  IconTranscript,
  IconTrash,
  IconTwitter,
  IconUnchat,
  IconUnlabel,
  IconUnuser,
  IconUpload,
  IconUser,
  IconUser2,
  IconUserCopyLeft,
  IconUserCouple,
  IconUserIdentity,
  IconUserTripple,
  IconUserRoundClock,
  IconUserRoundClose,
  IconUserRoundMinus,
  IconUserRoundPlus,
  IconUserRoundTick,
  IconUserRoundWarning,
  IconUserTone,
  IconUserTooltipBottom,
  IconUserTooltipLeft,
  IconUserTooltipRight,
  IconUserTooltipTop,
  IconVideo,
  IconVideoPlay,
  IconVoiceTone,
  IconWaba,
  IconWarningRounded,
  IconWarningTriangle,
  IconWhatsapp,
  IconUserCard,
  IconGroup3,
  IconGroup4,
  IconUserCopyRight,
  IconUserAdd,
  IconUserClose,
  IconUserMinus,
  IconUserNext,
  IconUserTick,
  IconUserLock,
  IconUserShield,
  IconUserFeedback,
  IconUserHashtag,
  IconCart,
  IconBagRectangle,
  IconBox,
  IconBoxAdd,
  IconPromo,
  IconLabel,
  IconDiscount,
  IconAwards,
  IconBoxEmpty,
  IconBasket,
  IconBasketAdd,
  IconInvoice,
  IconInvoice2,
  IconFlag2,
  IconBarcodeQR,
  IconBarcodeLine,
  IconDelivery,
  IconGift,
  IconBag,
  IconCollection,
  IconCollectionFill,
  IconCollectionDouble,
  IconLid,
  IconAtm,
  IconGif,
  IconStoreAdd,
  IconWarehouse,
  IconCooking,
  IconMedium,
  IconCoinDollar,
  IconOrganization,
  IconCareer,
  IconSuitcase,
  IconMixerFill,
  IconDrawer,
  IconCalculator,
  IconKeynoteAnalytic,
  IconKeynoteGraph,
  IconKeynoteParagraph,
  IconCalendarFill,
  IconCalendarSchedule,
  IconPrint,
  IconInvestment,
  IconGold,
  IconMoneys,
  IconSearchMoney,
  IconContactUser,
  IconContactEmail,
  IconAlarm,
  IconBag2,
  IconSuitcase2,
  IconSuitcase3,
  IconCoinDollar2,
  IconTarget,
  IconStempel,
  IconMoneyCoin,
  IconWallet2,
  IconMoneys2,
  IconChartGraph2,
  IconProgress,
  IconNetwork,
  IconMailDocument,
  IconMailInbox,
  IconWallet3,
  IconWallet4,
  IconCoins,
  IconBrankas,
  IconCoinEuro,
  IconCoinBitcoin,
  IconCoinPound,
  IconCoinIDR,
  IconPrintNota,
  IconPrintCard,
  IconDebitCard,
  IconPayment,
  IconMoneySave,
  IconSecurity,
  IconBank,
  IconNota,
  IconNotas,
  IconHandDebitCard,
  IconCalculator2,
  IconMultiDebitCard,
  IconHandCoins,
  IconPhoneDebitCard,
  IconPhoneCoins,
  IconMoneyDollar,
  IconMoneyEuro,
  IconMoneyPound,
  IconMoneyBitcoin,
  IconMoney,
  IconMoneyIDR,
  IconFlagMoneyDollar,
  IconFlagMoneyEuro,
  IconFlagMoneyBitcoin,
  IconFlagMoneyPound,
  IconFlagMoney,
  IconFlagMoneyIDR,
  IconSackDollar,
  IconSackEuro,
  IconSackBitcoin,
  IconSackPound,
  IconSackIDR,
  IconMoneysDouble,
  IconCoinsDouble,
  IconWallet,
  IconWalletAdd,
  IconGiftCoins,
  IconMoneyCheck,
  IconWebSearch,
  IconTarget2,
  IconSearch2,
  IconSeo,
  IconPerformance,
  IconRadar,
  IconPerformance2,
  IconSeo3,
  IconPerformance3,
  IconMagnet,
  IconWeb,
  IconEarth,
  IconOptimization,
  IconLeads2,
  IconAnalytic,
  IconWeb2,
  IconSeo2,
  IconTarget3,
  IconLeads,
  IconLike,
  IconDislike,
  IconEngagement,
  IconTurbo,
  IconPerformance4,
  IconWord,
  IconUnderline,
  IconBold,
  IconItalic,
  IconPageDoc,
  IconPageAdd,
  IconPageMinus,
  IconFolderOpen,
  IconPageOutline,
  IconPageTick,
  IconPageClose,
  IconFolder,
  IconRedCross,
  IconRedCrossBox,
  IconBagMedic,
  IconMonitorMedic,
  IconHeartChart,
  IconSyringe,
  IconDocumentMedic,
  IconShieldHeart,
  IconDNA,
  IconDrug,
  IconCapsule,
  IconHealthBox,
  IconStetoskop,
  IconNoSmoking,
  IconHospital,
  IconDental,
  IconBloodPlasma,
  IconAmbulance,
  IconLab,
  IconHealthCare,
  IconHeartCross,
  IconVirus,
} from '@aksara-ui/icons';

interface IconMap {
  name: string;
  children: React.ReactNode;
}

type IconMapObject = Record<string, IconMap[]>;

const aksaraIconMaps: IconMapObject = {
  ai: [
    { name: 'IconBot', children: <IconBot /> },
    { name: 'IconBot1', children: <IconBot1 /> },
    { name: 'IconBot2', children: <IconBot2 /> },
    { name: 'IconBotFlows', children: <IconBotFlows /> },
    { name: 'IconModule', children: <IconModule /> },
    { name: 'IconModuleLibrary', children: <IconModuleLibrary /> },
    { name: 'IconModuleTick', children: <IconModuleTick /> },
    { name: 'IconAPI', children: <IconAPI /> },
    { name: 'IconCMS', children: <IconCMS /> },
    { name: 'IconCommand', children: <IconCommand /> },
    { name: 'IconDeploy', children: <IconDeploy /> },
    { name: 'IconEnvironments', children: <IconEnvironments /> },
    { name: 'IconNLU', children: <IconNLU /> },
    { name: 'IconFingerprint', children: <IconFingerprint /> },
    { name: 'IconEyeRecognition', children: <IconEyeRecognition /> },
    { name: 'IconSound', children: <IconSound /> },
    { name: 'IconRobotic', children: <IconRobotic /> },
    { name: 'IconNeutral1', children: <IconNeutral1 /> },
    { name: 'IconNeutral2', children: <IconNeutral2 /> },
    { name: 'IconNeutral3', children: <IconNeutral3 /> },
    { name: 'IconHumanoid', children: <IconHumanoid /> },
    { name: 'IconHumanoid2', children: <IconHumanoid2 /> },
    { name: 'IconHumanoid3', children: <IconHumanoid3 /> },
    { name: 'IconBrain', children: <IconBrain /> },
    { name: 'IconBrainSimulation', children: <IconBrainSimulation /> },
    { name: 'IconIdeaBrain', children: <IconIdeaBrain /> },
    { name: 'IconIntelligence', children: <IconIntelligence /> },
    { name: 'IconAugmentedReality', children: <IconAugmentedReality /> },
  ],
  atoms: [
    { name: 'IconData', children: <IconData /> },
    { name: 'IconOrganism', children: <IconOrganism /> },
    { name: 'IconSingle', children: <IconSingle /> },
  ],
  basic: [
    { name: 'IconArrowDown', children: <IconArrowDown /> },
    { name: 'IconArrowLeft', children: <IconArrowLeft /> },
    { name: 'IconArrowRight', children: <IconArrowRight /> },
    { name: 'IconArrowUp', children: <IconArrowUp /> },
    { name: 'IconArrowDownRounded', children: <IconArrowDownRounded /> },
    { name: 'IconArrowLeftRounded', children: <IconArrowLeftRounded /> },
    { name: 'IconArrowRightRounded', children: <IconArrowRightRounded /> },
    { name: 'IconArrowUpRounded', children: <IconArrowUpRounded /> },
    { name: 'IconChevronDown', children: <IconChevronDown /> },
    { name: 'IconChevronLeft', children: <IconChevronLeft /> },
    { name: 'IconChevronRight', children: <IconChevronRight /> },
    { name: 'IconChevronUp', children: <IconChevronUp /> },
    { name: 'IconChevronDownRounded', children: <IconChevronDownRounded /> },
    { name: 'IconChevronLeftRounded', children: <IconChevronLeftRounded /> },
    { name: 'IconChevronRightRounded', children: <IconChevronRightRounded /> },
    { name: 'IconChevronUpRounded', children: <IconChevronUpRounded /> },
    { name: 'IconChevronDownFilled', children: <IconChevronDownFilled /> },
    { name: 'IconChevronLeftFilled', children: <IconChevronLeftFilled /> },
    { name: 'IconChevronRightFilled', children: <IconChevronRightFilled /> },
    { name: 'IconChevronUpFilled', children: <IconChevronUpFilled /> },
    { name: 'IconInfo', children: <IconInfo /> },
    { name: 'IconWarningTriangle', children: <IconWarningTriangle /> },
    { name: 'IconTickDouble', children: <IconTickDouble /> },
    { name: 'IconTickRounded', children: <IconTickRounded /> },
    { name: 'IconTickSingle', children: <IconTickSingle /> },
    { name: 'IconForward', children: <IconForward /> },
    { name: 'IconReply', children: <IconReply /> },
    { name: 'IconJumpNext', children: <IconJumpNext /> },
    { name: 'IconJumpPrevious', children: <IconJumpPrevious /> },
    { name: 'IconClose', children: <IconClose /> },
    { name: 'IconCloseRounded', children: <IconCloseRounded /> },
    { name: 'IconLoop', children: <IconLoop /> },
    { name: 'IconRefresh', children: <IconRefresh /> },
    { name: 'IconDrag', children: <IconDrag /> },
    { name: 'IconPlus', children: <IconPlus /> },
    { name: 'IconPlusRounded', children: <IconPlusRounded /> },
    { name: 'IconMinus', children: <IconMinus /> },
    { name: 'IconMinusRound', children: <IconMinusRound /> },
    { name: 'IconDragHorizontal', children: <IconDragHorizontal /> },
    { name: 'IconDragVertical', children: <IconDragVertical /> },
    { name: 'IconDropDown', children: <IconDropDown /> },
    { name: 'IconDropLeft', children: <IconDropLeft /> },
    { name: 'IconDropRight', children: <IconDropRight /> },
    { name: 'IconDropUp', children: <IconDropUp /> },
    { name: 'IconEyeClose', children: <IconEyeClose /> },
    { name: 'IconEyeOpen', children: <IconEyeOpen /> },
    { name: 'IconEyeUnvisible', children: <IconEyeUnvisible /> },
    { name: 'IconWarningRounded', children: <IconWarningRounded /> },
    { name: 'IconBell', children: <IconBell /> },
    { name: 'IconDownload', children: <IconDownload /> },
    { name: 'IconUpload', children: <IconUpload /> },
    { name: 'IconGear', children: <IconGear /> },
    { name: 'IconLock', children: <IconLock /> },
    { name: 'IconClock', children: <IconClock /> },
    { name: 'IconTrash', children: <IconTrash /> },
    { name: 'IconFilter', children: <IconFilter /> },
    { name: 'IconCalendar', children: <IconCalendar /> },
    { name: 'IconCalendarAdd', children: <IconCalendarAdd /> },
    { name: 'IconLogout', children: <IconLogout /> },
    { name: 'IconMixer', children: <IconMixer /> },
    { name: 'IconQuickForward', children: <IconQuickForward /> },
    { name: 'IconQuickReply', children: <IconQuickReply /> },
    { name: 'IconSearch', children: <IconSearch /> },
    { name: 'IconStar', children: <IconStar /> },
  ],
  businessfinance: [
    { name: 'IconChartPie', children: <IconChartPie /> },
    { name: 'IconChartGraph', children: <IconChartGraph /> },
    { name: 'IconChartGraph2', children: <IconChartGraph2 /> },
    { name: 'IconProgress', children: <IconProgress /> },
    { name: 'IconNetwork', children: <IconNetwork /> },
    { name: 'IconOrganization', children: <IconOrganization /> },
    { name: 'IconLocator', children: <IconLocator /> },
    { name: 'IconCareer', children: <IconCareer /> },
    { name: 'IconSuitcase', children: <IconSuitcase /> },
    { name: 'IconSuitcase2', children: <IconSuitcase2 /> },
    { name: 'IconSuitcase3', children: <IconSuitcase3 /> },
    { name: 'IconMixerFill', children: <IconMixerFill /> },
    { name: 'IconDrawer', children: <IconDrawer /> },
    { name: 'IconCalculator', children: <IconCalculator /> },
    { name: 'IconCalculator2', children: <IconCalculator2 /> },
    { name: 'IconKeynoteAnalytic', children: <IconKeynoteAnalytic /> },
    { name: 'IconKeynoteGraph', children: <IconKeynoteGraph /> },
    { name: 'IconKeynoteParagraph', children: <IconKeynoteParagraph /> },
    { name: 'IconCalendarFill', children: <IconCalendarFill /> },
    { name: 'IconCalendarSchedule', children: <IconCalendarSchedule /> },
    { name: 'IconPrint', children: <IconPrint /> },
    { name: 'IconPrintNota', children: <IconPrintNota /> },
    { name: 'IconPrintCard', children: <IconPrintCard /> },
    { name: 'IconInvestment', children: <IconInvestment /> },
    { name: 'IconGold', children: <IconGold /> },
    { name: 'IconMoneys', children: <IconMoneys /> },
    { name: 'IconSearchMoney', children: <IconSearchMoney /> },
    { name: 'IconContactUser', children: <IconContactUser /> },
    { name: 'IconContactEmail', children: <IconContactEmail /> },
    { name: 'IconAlarm', children: <IconAlarm /> },
    { name: 'IconBag2', children: <IconBag2 /> },
    { name: 'IconTarget', children: <IconTarget /> },
    { name: 'IconStempel', children: <IconStempel /> },
    { name: 'IconWalletAdd', children: <IconWalletAdd /> },
    { name: 'IconWallet', children: <IconWallet /> },
    { name: 'IconWallet2', children: <IconWallet2 /> },
    { name: 'IconWallet3', children: <IconWallet3 /> },
    { name: 'IconWallet4', children: <IconWallet4 /> },
    { name: 'IconMoneys2', children: <IconMoneys2 /> },
    { name: 'IconMailDocument', children: <IconMailDocument /> },
    { name: 'IconMailInbox', children: <IconMailInbox /> },
    { name: 'IconBrankas', children: <IconBrankas /> },
    { name: 'IconDebitCard', children: <IconDebitCard /> },
    { name: 'IconPayment', children: <IconPayment /> },
    { name: 'IconMoneySave', children: <IconMoneySave /> },
    { name: 'IconSecurity', children: <IconSecurity /> },
    { name: 'IconBank', children: <IconBank /> },
    { name: 'IconNota', children: <IconNota /> },
    { name: 'IconNotas', children: <IconNotas /> },
    { name: 'IconHandDebitCard', children: <IconHandDebitCard /> },
    { name: 'IconMultiDebitCard', children: <IconMultiDebitCard /> },
    { name: 'IconCoins', children: <IconCoins /> },
    { name: 'IconCoinDollar', children: <IconCoinDollar /> },
    { name: 'IconCoinDollar2', children: <IconCoinDollar2 /> },
    { name: 'IconCoinEuro', children: <IconCoinEuro /> },
    { name: 'IconCoinBitcoin', children: <IconCoinBitcoin /> },
    { name: 'IconCoinPound', children: <IconCoinPound /> },
    { name: 'IconCoinIDR', children: <IconCoinIDR /> },
    { name: 'IconMoneyCoin', children: <IconMoneyCoin /> },
    { name: 'IconHandCoins', children: <IconHandCoins /> },
    { name: 'IconPhoneDebitCard', children: <IconPhoneDebitCard /> },
    { name: 'IconPhoneCoins', children: <IconPhoneCoins /> },
    { name: 'IconMoneyDollar', children: <IconMoneyDollar /> },
    { name: 'IconMoneyEuro', children: <IconMoneyEuro /> },
    { name: 'IconMoneyBitcoin', children: <IconMoneyBitcoin /> },
    { name: 'IconMoneyPound', children: <IconMoneyPound /> },
    { name: 'IconMoney', children: <IconMoney /> },
    { name: 'IconMoneyIDR', children: <IconMoneyIDR /> },
    { name: 'IconFlagMoneyDollar', children: <IconFlagMoneyDollar /> },
    { name: 'IconFlagMoneyEuro', children: <IconFlagMoneyEuro /> },
    { name: 'IconFlagMoneyBitcoin', children: <IconFlagMoneyBitcoin /> },
    { name: 'IconFlagMoneyPound', children: <IconFlagMoneyPound /> },
    { name: 'IconFlagMoney', children: <IconFlagMoney /> },
    { name: 'IconFlagMoneyIDR', children: <IconFlagMoneyIDR /> },
    { name: 'IconSackDollar', children: <IconSackDollar /> },
    { name: 'IconSackEuro', children: <IconSackEuro /> },
    { name: 'IconSackBitcoin', children: <IconSackBitcoin /> },
    { name: 'IconSackIDR', children: <IconSackIDR /> },
    { name: 'IconSackPound', children: <IconSackPound /> },
    { name: 'IconMoneysDouble', children: <IconMoneysDouble /> },
    { name: 'IconCoinsDouble', children: <IconCoinsDouble /> },
    { name: 'IconGiftCoins', children: <IconGiftCoins /> },
    { name: 'IconMoneyCheck', children: <IconMoneyCheck /> },
  ],
  chat: [
    { name: 'IconBubble', children: <IconBubble /> },
    { name: 'IconBubble2', children: <IconBubble2 /> },
    { name: 'IconBubble3', children: <IconBubble3 /> },
    { name: 'IconBubble4', children: <IconBubble4 /> },
    { name: 'IconBubble5', children: <IconBubble5 /> },
    { name: 'IconBubble6', children: <IconBubble6 /> },
    { name: 'IconBubble7', children: <IconBubble7 /> },
    { name: 'IconBubbleCheck', children: <IconBubbleCheck /> },
    { name: 'IconBubbleLove', children: <IconBubbleLove /> },
    { name: 'IconBubbleClose', children: <IconBubbleClose /> },
    { name: 'IconBubbleEdit', children: <IconBubbleEdit /> },
    { name: 'IconBubblePlus', children: <IconBubblePlus /> },
    { name: 'IconBubbleTick', children: <IconBubbleTick /> },
    { name: 'IconConversation', children: <IconConversation /> },
    { name: 'IconConversation3', children: <IconConversation3 /> },
    { name: 'IconConversation1', children: <IconConversation1 /> },
    { name: 'IconConversation2', children: <IconConversation2 /> },
    { name: 'IconConversation4', children: <IconConversation4 /> },
    { name: 'IconEntities', children: <IconEntities /> },
    { name: 'IconFAQ', children: <IconFAQ /> },
    { name: 'IconNLUs', children: <IconNLUs /> },
    { name: 'IconPhrase', children: <IconPhrase /> },
    { name: 'IconTranscript', children: <IconTranscript /> },
    { name: 'IconUnchat', children: <IconUnchat /> },
    { name: 'IconWaba', children: <IconWaba /> },
    { name: 'IconTooltipBottom', children: <IconTooltipBottom /> },
    { name: 'IconTooltipLeft', children: <IconTooltipLeft /> },
    { name: 'IconTooltipRight', children: <IconTooltipRight /> },
    { name: 'IconTooltipTop', children: <IconTooltipTop /> },
    { name: 'IconTooltipLove', children: <IconTooltipLove /> },
    { name: 'IconMessageBot', children: <IconMessageBot /> },
    { name: 'IconMessageTemplate', children: <IconMessageTemplate /> },
    { name: 'IconNLUTrait', children: <IconNLUTrait /> },
  ],
  doc: [
    { name: 'IconDocAdd', children: <IconDocAdd /> },
    { name: 'IconDoc', children: <IconDoc /> },
    { name: 'IconList', children: <IconList /> },
    { name: 'IconHistory', children: <IconHistory /> },
    { name: 'IconTextData', children: <IconTextData /> },
    { name: 'IconPen', children: <IconPen /> },
    { name: 'IconTextBox', children: <IconTextBox /> },
    { name: 'IconTextArea', children: <IconTextArea /> },
    { name: 'IconDictionary', children: <IconDictionary /> },
    { name: 'IconTextList', children: <IconTextList /> },
    { name: 'IconUnlabel', children: <IconUnlabel /> },
    { name: 'IconDesign', children: <IconDesign /> },
    { name: 'IconWord', children: <IconWord /> },
    { name: 'IconUnderline', children: <IconUnderline /> },
    { name: 'IconBold', children: <IconBold /> },
    { name: 'IconItalic', children: <IconItalic /> },
    { name: 'IconFolder', children: <IconFolder /> },
    { name: 'IconFolderOpen', children: <IconFolderOpen /> },
    { name: 'IconPageOutline', children: <IconPageOutline /> },
    { name: 'IconPage', children: <IconPage /> },
    { name: 'IconPageDoc', children: <IconPageDoc /> },
    { name: 'IconPageAdd', children: <IconPageAdd /> },
    { name: 'IconPageMinus', children: <IconPageMinus /> },
    { name: 'IconPageClose', children: <IconPageClose /> },
    { name: 'IconPageTick', children: <IconPageTick /> },
  ],
  ecommerce: [
    { name: 'IconCartAdd', children: <IconCartAdd /> },
    { name: 'IconCart', children: <IconCart /> },
    { name: 'IconCamera', children: <IconCamera /> },
    { name: 'IconBagRectangle', children: <IconBagRectangle /> },
    { name: 'IconBox', children: <IconBox /> },
    { name: 'IconBoxAdd', children: <IconBoxAdd /> },
    { name: 'IconPromo', children: <IconPromo /> },
    { name: 'IconLabel', children: <IconLabel /> },
    { name: 'IconDiscount', children: <IconDiscount /> },
    { name: 'IconAwards', children: <IconAwards /> },
    { name: 'IconBoxEmpty', children: <IconBoxEmpty /> },
    { name: 'IconBasket', children: <IconBasket /> },
    { name: 'IconBasketAdd', children: <IconBasketAdd /> },
    { name: 'IconInvoice', children: <IconInvoice /> },
    { name: 'IconInvoice2', children: <IconInvoice2 /> },
    { name: 'IconFlag2', children: <IconFlag2 /> },
    { name: 'IconBarcodeQR', children: <IconBarcodeQR /> },
    { name: 'IconBarcodeLine', children: <IconBarcodeLine /> },
    { name: 'IconDelivery', children: <IconDelivery /> },
    { name: 'IconGift', children: <IconGift /> },
    { name: 'IconBag', children: <IconBag /> },
    { name: 'IconCollectionFill', children: <IconCollectionFill /> },
    { name: 'IconCollection', children: <IconCollection /> },
    { name: 'IconCollectionDouble', children: <IconCollectionDouble /> },
    { name: 'IconLid', children: <IconLid /> },
    { name: 'IconAtm', children: <IconAtm /> },
    { name: 'IconGif', children: <IconGif /> },
    { name: 'IconStoreAdd', children: <IconStoreAdd /> },
    { name: 'IconStore', children: <IconStore /> },
    { name: 'IconWarehouse', children: <IconWarehouse /> },
    { name: 'IconCooking', children: <IconCooking /> },
  ],
  marketing: [
    { name: 'IconWebSearch', children: <IconWebSearch /> },
    { name: 'IconSearch2', children: <IconSearch2 /> },
    { name: 'IconTarget2', children: <IconTarget2 /> },
    { name: 'IconTarget3', children: <IconTarget3 /> },
    { name: 'IconSeo', children: <IconSeo /> },
    { name: 'IconSeo2', children: <IconSeo2 /> },
    { name: 'IconSeo3', children: <IconSeo3 /> },
    { name: 'IconPerformance', children: <IconPerformance /> },
    { name: 'IconPerformance2', children: <IconPerformance2 /> },
    { name: 'IconPerformance3', children: <IconPerformance3 /> },
    { name: 'IconPerformance4', children: <IconPerformance4 /> },
    { name: 'IconRadar', children: <IconRadar /> },
    { name: 'IconMagnet', children: <IconMagnet /> },
    { name: 'IconWeb', children: <IconWeb /> },
    { name: 'IconWeb2', children: <IconWeb2 /> },
    { name: 'IconEarth', children: <IconEarth /> },
    { name: 'IconOptimization', children: <IconOptimization /> },
    { name: 'IconLeads', children: <IconLeads /> },
    { name: 'IconLeads2', children: <IconLeads2 /> },
    { name: 'IconAnalytic', children: <IconAnalytic /> },
    { name: 'IconLike', children: <IconLike /> },
    { name: 'IconDislike', children: <IconDislike /> },
    { name: 'IconEngagement', children: <IconEngagement /> },
    { name: 'IconCrystalLamp', children: <IconCrystalLamp /> },
    { name: 'IconCampaign', children: <IconCampaign /> },
    { name: 'IconTurbo', children: <IconTurbo /> },
  ],
  media: [
    { name: 'IconAudio', children: <IconAudio /> },
    { name: 'IconBriefcase', children: <IconBriefcase /> },
    { name: 'IconCarousel', children: <IconCarousel /> },
    { name: 'IconCarouselDynamic', children: <IconCarouselDynamic /> },
    { name: 'IconCarouselImage', children: <IconCarouselImage /> },
    { name: 'IconCircle', children: <IconCircle /> },
    { name: 'IconCloudUpload', children: <IconCloudUpload /> },
    { name: 'IconCopy', children: <IconCopy /> },
    { name: 'IconDiamond', children: <IconDiamond /> },
    { name: 'IconDropdown', children: <IconDropdown /> },
    { name: 'IconEmoji', children: <IconEmoji /> },
    { name: 'IconFlag', children: <IconFlag /> },
    { name: 'IconImageAdd', children: <IconImageAdd /> },
    { name: 'IconImage', children: <IconImage /> },
    { name: 'IconImageMap', children: <IconImageMap /> },
    { name: 'IconGuides', children: <IconGuides /> },
    { name: 'IconLink', children: <IconLink /> },
    { name: 'IconLinkHorizontal', children: <IconLinkHorizontal /> },
    { name: 'IconLinkVertical', children: <IconLinkVertical /> },
    { name: 'IconMarker', children: <IconMarker /> },
    { name: 'IconMessage', children: <IconMessage /> },
    { name: 'IconPaperPlane', children: <IconPaperPlane /> },
    { name: 'IconShare', children: <IconShare /> },
    { name: 'IconSend', children: <IconSend /> },
    { name: 'IconSave', children: <IconSave /> },
    { name: 'IconPersistentMenu', children: <IconPersistentMenu /> },
    { name: 'IconSlinder', children: <IconSlinder /> },
    { name: 'IconToggle', children: <IconToggle /> },
    { name: 'IconButton', children: <IconButton /> },
    { name: 'IconSquare', children: <IconSquare /> },
    { name: 'IconSticker', children: <IconSticker /> },
    { name: 'IconTemplate', children: <IconTemplate /> },
    { name: 'IconTemplateMenu', children: <IconTemplateMenu /> },
    { name: 'IconVideo', children: <IconVideo /> },
    { name: 'IconVideoPlay', children: <IconVideoPlay /> },
    { name: 'IconShutdown', children: <IconShutdown /> },
    { name: 'IconPlug', children: <IconPlug /> },
    { name: 'IconOutgoing', children: <IconOutgoing /> },
    { name: 'IconOutgoingFill', children: <IconOutgoingFill /> },
  ],
  medicine: [
    { name: 'IconRedCross', children: <IconRedCross /> },
    { name: 'IconRedCrossBox', children: <IconRedCrossBox /> },
    { name: 'IconBagMedic', children: <IconBagMedic /> },
    { name: 'IconMonitorMedic', children: <IconMonitorMedic /> },
    { name: 'IconHeartChart', children: <IconHeartChart /> },
    { name: 'IconSyringe', children: <IconSyringe /> },
    { name: 'IconDocumentMedic', children: <IconDocumentMedic /> },
    { name: 'IconShieldHeart', children: <IconShieldHeart /> },
    { name: 'IconDNA', children: <IconDNA /> },
    { name: 'IconDrug', children: <IconDrug /> },
    { name: 'IconCapsule', children: <IconCapsule /> },
    { name: 'IconHealthBox', children: <IconHealthBox /> },
    { name: 'IconStetoskop', children: <IconStetoskop /> },
    { name: 'IconNoSmoking', children: <IconNoSmoking /> },
    { name: 'IconHospital', children: <IconHospital /> },
    { name: 'IconDental', children: <IconDental /> },
    { name: 'IconBloodPlasma', children: <IconBloodPlasma /> },
    { name: 'IconAmbulance', children: <IconAmbulance /> },
    { name: 'IconLab', children: <IconLab /> },
    { name: 'IconHealthCare', children: <IconHealthCare /> },
    { name: 'IconVirus', children: <IconVirus /> },
    { name: 'IconHeartCross', children: <IconHeartCross /> },
  ],
  menu: [
    { name: 'IconMenu', children: <IconMenu /> },
    { name: 'IconMenuFilter', children: <IconMenuFilter /> },
    { name: 'IconFlowerGrid', children: <IconFlowerGrid /> },
    { name: 'IconGrid', children: <IconGrid /> },
    { name: 'IconHamburger', children: <IconHamburger /> },
    { name: 'IconKebab', children: <IconKebab /> },
    { name: 'IconKebabHorizontal', children: <IconKebabHorizontal /> },
    { name: 'IconKebabRounded', children: <IconKebabRounded /> },
  ],
  social: [
    { name: 'IconBehance', children: <IconBehance /> },
    { name: 'IconDribble', children: <IconDribble /> },
    { name: 'IconFacebookMessenger', children: <IconFacebookMessenger /> },
    { name: 'IconFacebook', children: <IconFacebook /> },
    { name: 'IconGithub', children: <IconGithub /> },
    { name: 'IconInstagram', children: <IconInstagram /> },
    { name: 'IconLine', children: <IconLine /> },
    { name: 'IconLinkedin', children: <IconLinkedin /> },
    { name: 'IconSlack', children: <IconSlack /> },
    { name: 'IconTwitter', children: <IconTwitter /> },
    { name: 'IconWhatsapp', children: <IconWhatsapp /> },
    { name: 'IconMedium', children: <IconMedium /> },
  ],
  user: [
    { name: 'IconAudience', children: <IconAudience /> },
    { name: 'IconClient', children: <IconClient /> },
    { name: 'IconUser', children: <IconUser /> },
    { name: 'IconUser2', children: <IconUser2 /> },
    { name: 'IconUserIdentity', children: <IconUserIdentity /> },
    { name: 'IconUserCouple', children: <IconUserCouple /> },
    { name: 'IconUserTripple', children: <IconUserTripple /> },
    { name: 'IconCollaboration', children: <IconCollaboration /> },
    { name: 'IconUserTone', children: <IconUserTone /> },
    { name: 'IconVoiceTone', children: <IconVoiceTone /> },
    { name: 'IconUserCard', children: <IconUserCard /> },
    { name: 'IconGroup3', children: <IconGroup3 /> },
    { name: 'IconGroup4', children: <IconGroup4 /> },
    { name: 'IconUserCopyLeft', children: <IconUserCopyLeft /> },
    { name: 'IconUserCopyRight', children: <IconUserCopyRight /> },
    { name: 'IconUserTooltipBottom', children: <IconUserTooltipBottom /> },
    { name: 'IconUserTooltipTop', children: <IconUserTooltipTop /> },
    { name: 'IconUserTooltipLeft', children: <IconUserTooltipLeft /> },
    { name: 'IconUserTooltipRight', children: <IconUserTooltipRight /> },
    { name: 'IconUnuser', children: <IconUnuser /> },
    { name: 'IconUserAdd', children: <IconUserAdd /> },
    { name: 'IconUserMinus', children: <IconUserMinus /> },
    { name: 'IconUserClose', children: <IconUserClose /> },
    { name: 'IconUserTick', children: <IconUserTick /> },
    { name: 'IconUserNext', children: <IconUserNext /> },
    { name: 'IconUserLock', children: <IconUserLock /> },
    { name: 'IconUserShield', children: <IconUserShield /> },
    { name: 'IconUserFeedback', children: <IconUserFeedback /> },
    { name: 'IconUserHashtag', children: <IconUserHashtag /> },
    { name: 'IconUserRoundMinus', children: <IconUserRoundMinus /> },
    { name: 'IconUserRoundClose', children: <IconUserRoundClose /> },
    { name: 'IconUserRoundTick', children: <IconUserRoundTick /> },
    { name: 'IconUserRoundWarning', children: <IconUserRoundWarning /> },
    { name: 'IconUserRoundPlus', children: <IconUserRoundPlus /> },
    { name: 'IconUserRoundClock', children: <IconUserRoundClock /> },
  ],
};

export default aksaraIconMaps;
