import * as React from 'react';

import {
  IconAnalytic,
  IconAPI,
  IconArrowDown,
  IconArrowDownRounded,
  IconArrowLeft,
  IconArrowLeftRounded,
  IconArrowRight,
  IconArrowRightRounded,
  IconArrowUp,
  IconArrowUpRounded,
  IconAudience,
  IconAudio,
  IconBehance,
  IconBell,
  IconBot,
  IconBotFlows,
  IconBriefcase,
  IconBubble,
  IconBubbleCheck,
  IconBubbleClose,
  IconBubbleEdit,
  IconBubblePlus,
  IconButton,
  IconCalendar,
  IconCalendarAdd,
  IconCamera,
  IconCampaign,
  IconCarousel,
  IconCarouselDynamic,
  IconCarouselImage,
  IconChartGraph,
  IconChartPie,
  IconChevronDown,
  IconChevronDownFilled,
  IconChevronDownRounded,
  IconChevronLeft,
  IconChevronLeftFilled,
  IconChevronLeftRounded,
  IconChevronRight,
  IconChevronRightFilled,
  IconChevronRightRounded,
  IconChevronUp,
  IconChevronUpFilled,
  IconChevronUpRounded,
  IconCircle,
  IconClient,
  IconClock,
  IconClose,
  IconCloseRounded,
  IconCloudUpload,
  IconCMS,
  IconCommand,
  IconConversation,
  IconCopy,
  IconCrmBot,
  IconCrystalLamp,
  IconData,
  IconDeploy,
  IconDesign,
  IconDiamond,
  IconDictionary,
  IconDoc,
  IconDocAdd,
  IconDownload,
  IconDrag,
  IconDragHorizontal,
  IconDragVertical,
  IconDribble,
  IconDropDown,
  IconDropdown,
  IconDropLeft,
  IconDropRight,
  IconDropUp,
  IconEmoji,
  IconEntities,
  IconEnvironments,
  IconError,
  IconEyeClose,
  IconEyeOpen,
  IconEyeUnvisible,
  IconFacebook,
  IconFacebookMessenger,
  IconFAQ,
  IconFilter,
  IconFlag,
  IconFlowerGrid,
  IconForward,
  IconGear,
  IconGithub,
  IconGrid,
  IconGuides,
  IconHamburger,
  IconHistory,
  IconHistoryPanel,
  IconIdea,
  IconImage,
  IconImageAdd,
  IconImageMap,
  IconInfo,
  IconInstagram,
  IconJumpNext,
  IconJumpPrevious,
  IconKebab,
  IconKebabHorizontal,
  IconKebabRounded,
  IconLine,
  IconLink,
  IconLinkedin,
  IconLinkHorizontal,
  IconLinkVertical,
  IconList,
  IconLocator,
  IconLock,
  IconLogout,
  IconLoop,
  IconMarker,
  IconMenu,
  IconMenuFilter,
  IconMessage,
  IconMessageBot,
  IconMessageTemplate,
  IconMethods,
  IconMinus,
  IconMinusRound,
  IconMixer,
  IconModule,
  IconModuleLibrary,
  IconModuleTick,
  IconNLU,
  IconNLUs,
  IconNLUTrait,
  IconOrganism,
  IconOutgoing,
  IconOutgoingFill,
  IconPages,
  IconPaperPlane,
  IconPen,
  IconPersistentMenu,
  IconPhrase,
  IconPie,
  IconPlug,
  IconPlus,
  IconPlusRounded,
  IconQuickForward,
  IconQuickReply,
  IconRefresh,
  IconReply,
  IconSave,
  IconSearch,
  IconSend,
  IconShutdown,
  IconSingle,
  IconSlack,
  IconSlinder,
  IconSquare,
  IconStar,
  IconSticker,
  IconStore,
  IconTemplate,
  IconTemplateMenu,
  IconTextArea,
  IconTextBox,
  IconTextData,
  IconTextList,
  IconTickDouble,
  IconTickRounded,
  IconTickSingle,
  IconToggle,
  IconTranscript,
  IconTrash,
  IconTwitter,
  IconUnlabel,
  IconUpload,
  IconUser,
  IconVideo,
  IconVideoPlay,
  IconVoiceTone,
  IconWaba,
  IconWarningRounded,
  IconWarningTriangle,
  IconWhatsapp,
} from '@aksara-ui/icons';

interface IconMap {
  name: string;
  children: React.ReactNode;
}

type IconMapObject = Record<string, IconMap[]>;

const aksaraIconMaps: IconMapObject = {
  ai: [
    { name: 'IconBot', children: <IconBot /> },
    { name: 'IconBotFlows', children: <IconBotFlows /> },
    { name: 'IconModule', children: <IconModule /> },
    { name: 'IconModuleLibrary', children: <IconModuleLibrary /> },
    { name: 'IconModuleTick', children: <IconModuleTick /> },
    { name: 'IconAPI', children: <IconAPI /> },
    { name: 'IconCMS', children: <IconCMS /> },
    { name: 'IconCommand', children: <IconCommand /> },
    { name: 'IconDeploy', children: <IconDeploy /> },
    { name: 'IconEnvironments', children: <IconEnvironments /> },
    { name: 'IconNLU', children: <IconNLU /> },
  ],
  atoms: [
    { name: 'IconData', children: <IconData /> },
    { name: 'IconOrganism', children: <IconOrganism /> },
    { name: 'IconSingle', children: <IconSingle /> },
  ],
  basic: [
    { name: 'IconArrowDown', children: <IconArrowDown /> },
    { name: 'IconArrowLeft', children: <IconArrowLeft /> },
    { name: 'IconArrowRight', children: <IconArrowRight /> },
    { name: 'IconArrowUp', children: <IconArrowUp /> },
    { name: 'IconArrowDownRounded', children: <IconArrowDownRounded /> },
    { name: 'IconArrowLeftRounded', children: <IconArrowLeftRounded /> },
    { name: 'IconArrowRightRounded', children: <IconArrowRightRounded /> },
    { name: 'IconArrowUpRounded', children: <IconArrowUpRounded /> },
    { name: 'IconChevronDown', children: <IconChevronDown /> },
    { name: 'IconChevronLeft', children: <IconChevronLeft /> },
    { name: 'IconChevronRight', children: <IconChevronRight /> },
    { name: 'IconChevronUp', children: <IconChevronUp /> },
    { name: 'IconChevronDownRounded', children: <IconChevronDownRounded /> },
    { name: 'IconChevronLeftRounded', children: <IconChevronLeftRounded /> },
    { name: 'IconChevronRightRounded', children: <IconChevronRightRounded /> },
    { name: 'IconChevronUpRounded', children: <IconChevronUpRounded /> },
    { name: 'IconChevronDownFilled', children: <IconChevronDownFilled /> },
    { name: 'IconChevronLeftFilled', children: <IconChevronLeftFilled /> },
    { name: 'IconChevronRightFilled', children: <IconChevronRightFilled /> },
    { name: 'IconChevronUpFilled', children: <IconChevronUpFilled /> },
    { name: 'IconInfo', children: <IconInfo /> },
    { name: 'IconWarningTriangle', children: <IconWarningTriangle /> },
    { name: 'IconTickDouble', children: <IconTickDouble /> },
    { name: 'IconTickRounded', children: <IconTickRounded /> },
    { name: 'IconTickSingle', children: <IconTickSingle /> },
    { name: 'IconForward', children: <IconForward /> },
    { name: 'IconReply', children: <IconReply /> },
    { name: 'IconJumpNext', children: <IconJumpNext /> },
    { name: 'IconJumpPrevious', children: <IconJumpPrevious /> },
    { name: 'IconClose', children: <IconClose /> },
    { name: 'IconCloseRounded', children: <IconCloseRounded /> },
    { name: 'IconLoop', children: <IconLoop /> },
    { name: 'IconRefresh', children: <IconRefresh /> },
    { name: 'IconDrag', children: <IconDrag /> },
    { name: 'IconPlus', children: <IconPlus /> },
    { name: 'IconPlusRounded', children: <IconPlusRounded /> },
    { name: 'IconMinus', children: <IconMinus /> },
    { name: 'IconMinusRound', children: <IconMinusRound /> },
    { name: 'IconDragHorizontal', children: <IconDragHorizontal /> },
    { name: 'IconDragVertical', children: <IconDragVertical /> },
    { name: 'IconDropDown', children: <IconDropDown /> },
    { name: 'IconDropLeft', children: <IconDropLeft /> },
    { name: 'IconDropRight', children: <IconDropRight /> },
    { name: 'IconDropUp', children: <IconDropUp /> },
    { name: 'IconEyeClose', children: <IconEyeClose /> },
    { name: 'IconEyeOpen', children: <IconEyeOpen /> },
    { name: 'IconEyeUnvisible', children: <IconEyeUnvisible /> },
    { name: 'IconWarningRounded', children: <IconWarningRounded /> },
    { name: 'IconBell', children: <IconBell /> },
    { name: 'IconDownload', children: <IconDownload /> },
    { name: 'IconUpload', children: <IconUpload /> },
    { name: 'IconGear', children: <IconGear /> },
    { name: 'IconLock', children: <IconLock /> },
    { name: 'IconClock', children: <IconClock /> },
    { name: 'IconTrash', children: <IconTrash /> },
    { name: 'IconFilter', children: <IconFilter /> },
    { name: 'IconCalendar', children: <IconCalendar /> },
    { name: 'IconCalendarAdd', children: <IconCalendarAdd /> },
    { name: 'IconLogout', children: <IconLogout /> },
    { name: 'IconMixer', children: <IconMixer /> },
    { name: 'IconQuickForward', children: <IconQuickForward /> },
    { name: 'IconQuickReply', children: <IconQuickReply /> },
    { name: 'IconSearch', children: <IconSearch /> },
    { name: 'IconStar', children: <IconStar /> },
    { name: 'IconUnlabel', children: <IconUnlabel /> },
  ],
  bubble: [
    { name: 'IconBubble', children: <IconBubble /> },
    { name: 'IconBubbleCheck', children: <IconBubbleCheck /> },
    { name: 'IconBubbleClose', children: <IconBubbleClose /> },
    { name: 'IconBubbleEdit', children: <IconBubbleEdit /> },
    { name: 'IconBubblePlus', children: <IconBubblePlus /> },
    { name: 'IconConversation', children: <IconConversation /> },
    { name: 'IconEntities', children: <IconEntities /> },
    { name: 'IconFAQ', children: <IconFAQ /> },
    { name: 'IconNLUs', children: <IconNLUs /> },
    { name: 'IconPhrase', children: <IconPhrase /> },
    { name: 'IconTranscript', children: <IconTranscript /> },
    { name: 'IconWaba', children: <IconWaba /> },
    { name: 'IconMessageBot', children: <IconMessageBot /> },
    { name: 'IconMessageTemplate', children: <IconMessageTemplate /> },
    { name: 'IconNLUTrait', children: <IconNLUTrait /> },
  ],
  chart: [
    { name: 'IconChartGraph', children: <IconChartGraph /> },
    { name: 'IconChartPie', children: <IconChartPie /> },
  ],
  doc: [
    { name: 'IconDoc', children: <IconDoc /> },
    { name: 'IconDocAdd', children: <IconDocAdd /> },
    { name: 'IconDictionary', children: <IconDictionary /> },
    { name: 'IconHistory', children: <IconHistory /> },
    { name: 'IconList', children: <IconList /> },
    { name: 'IconPages', children: <IconPages /> },
    { name: 'IconPen', children: <IconPen /> },
    { name: 'IconTextArea', children: <IconTextArea /> },
    { name: 'IconTextBox', children: <IconTextBox /> },
    { name: 'IconTextData', children: <IconTextData /> },
    { name: 'IconTextList', children: <IconTextList /> },
  ],
  media: [
    { name: 'IconAudio', children: <IconAudio /> },
    { name: 'IconBriefcase', children: <IconBriefcase /> },
    { name: 'IconCamera', children: <IconCamera /> },
    { name: 'IconCampaign', children: <IconCampaign /> },
    { name: 'IconCarousel', children: <IconCarousel /> },
    { name: 'IconCarouselDynamic', children: <IconCarouselDynamic /> },
    { name: 'IconCarouselImage', children: <IconCarouselImage /> },
    { name: 'IconCircle', children: <IconCircle /> },
    { name: 'IconCloudUpload', children: <IconCloudUpload /> },
    { name: 'IconCopy', children: <IconCopy /> },
    { name: 'IconCrystalLamp', children: <IconCrystalLamp /> },
    { name: 'IconDesign', children: <IconDesign /> },
    { name: 'IconDiamond', children: <IconDiamond /> },
    { name: 'IconDropdown', children: <IconDropdown /> },
    { name: 'IconEmoji', children: <IconEmoji /> },
    { name: 'IconFlag', children: <IconFlag /> },
    { name: 'IconImageAdd', children: <IconImageAdd /> },
    { name: 'IconImage', children: <IconImage /> },
    { name: 'IconImageMap', children: <IconImageMap /> },
    { name: 'IconGuides', children: <IconGuides /> },
    { name: 'IconLink', children: <IconLink /> },
    { name: 'IconLinkHorizontal', children: <IconLinkHorizontal /> },
    { name: 'IconLinkVertical', children: <IconLinkVertical /> },
    { name: 'IconLocator', children: <IconLocator /> },
    { name: 'IconMarker', children: <IconMarker /> },
    { name: 'IconMessage', children: <IconMessage /> },
    { name: 'IconPaperPlane', children: <IconPaperPlane /> },
    { name: 'IconSend', children: <IconSend /> },
    { name: 'IconSave', children: <IconSave /> },
    { name: 'IconPersistentMenu', children: <IconPersistentMenu /> },
    { name: 'IconSlinder', children: <IconSlinder /> },
    { name: 'IconToggle', children: <IconToggle /> },
    { name: 'IconButton', children: <IconButton /> },
    { name: 'IconSquare', children: <IconSquare /> },
    { name: 'IconSticker', children: <IconSticker /> },
    { name: 'IconStore', children: <IconStore /> },
    { name: 'IconTemplate', children: <IconTemplate /> },
    { name: 'IconTemplateMenu', children: <IconTemplateMenu /> },
    { name: 'IconVideo', children: <IconVideo /> },
    { name: 'IconVideoPlay', children: <IconVideoPlay /> },
    { name: 'IconShutdown', children: <IconShutdown /> },
    { name: 'IconPlug', children: <IconPlug /> },
    { name: 'IconOutgoing', children: <IconOutgoing /> },
    { name: 'IconOutgoingFill', children: <IconOutgoingFill /> },
  ],
  menu: [
    { name: 'IconMenu', children: <IconMenu /> },
    { name: 'IconMenuFilter', children: <IconMenuFilter /> },
    { name: 'IconFlowerGrid', children: <IconFlowerGrid /> },
    { name: 'IconGrid', children: <IconGrid /> },
    { name: 'IconHamburger', children: <IconHamburger /> },
    { name: 'IconKebab', children: <IconKebab /> },
    { name: 'IconKebabHorizontal', children: <IconKebabHorizontal /> },
    { name: 'IconKebabRounded', children: <IconKebabRounded /> },
  ],
  panel: [
    { name: 'IconAnalytic', children: <IconAnalytic /> },
    { name: 'IconCrmBot', children: <IconCrmBot /> },
    { name: 'IconError', children: <IconError /> },
    { name: 'IconHistoryPanel', children: <IconHistoryPanel /> },
    { name: 'IconIdea', children: <IconIdea /> },
    { name: 'IconMethods', children: <IconMethods /> },
    { name: 'IconPie', children: <IconPie /> },
  ],
  social: [
    { name: 'IconBehance', children: <IconBehance /> },
    { name: 'IconDribble', children: <IconDribble /> },
    { name: 'IconFacebookMessenger', children: <IconFacebookMessenger /> },
    { name: 'IconFacebook', children: <IconFacebook /> },
    { name: 'IconGithub', children: <IconGithub /> },
    { name: 'IconInstagram', children: <IconInstagram /> },
    { name: 'IconLine', children: <IconLine /> },
    { name: 'IconLinkedin', children: <IconLinkedin /> },
    { name: 'IconSlack', children: <IconSlack /> },
    { name: 'IconTwitter', children: <IconTwitter /> },
    { name: 'IconWhatsapp', children: <IconWhatsapp /> },
  ],
  user: [
    { name: 'IconAudience', children: <IconAudience /> },
    { name: 'IconClient', children: <IconClient /> },
    { name: 'IconUser', children: <IconUser /> },
    { name: 'IconVoiceTone', children: <IconVoiceTone /> },
  ],
};

export default aksaraIconMaps;
