export * from './carousel';
export * from './image';
export * from './link';
export * from './outgoing';
export * from './template';

export { default as IconAudio } from './IconAudio';
export { default as IconBriefcase } from './IconBriefcase';
export { default as IconButton } from './IconButton';
export { default as IconCircle } from './IconCircle';
export { default as IconCloudUpload } from './IconCloudUpload';
export { default as IconCopy } from './IconCopy';
export { default as IconDiamond } from './IconDiamond';
export { default as IconDropdown } from './IconDropdown';
export { default as IconEmoji } from './IconEmoji';
export { default as IconFlag } from './IconFlag';
export { default as IconGuides } from './IconGuides';
export { default as IconMarker } from './IconMarker';
export { default as IconMessage } from './IconMessage';
export { default as IconPaperPlane } from './IconPaperPlane';
export { default as IconPersistentMenu } from './IconPersistentMenu';
export { default as IconPlug } from './IconPlug';
export { default as IconSave } from './IconSave';
export { default as IconSend } from './IconSend';
export { default as IconShare } from './IconShare';
export { default as IconShutdown } from './IconShutdown';
export { default as IconSlinder } from './IconSlinder';
export { default as IconSquare } from './IconSquare';
export { default as IconSticker } from './IconSticker';
export { default as IconToggle } from './IconToggle';
export { default as IconVideo } from './IconVideo';
export { default as IconVideoPlay } from './IconVideoPlay';
