export * from './carousel';
export * from './image';
export * from './template';

export { default as IconAudio } from './IconAudio';
export { default as IconBriefcase } from './IconBriefcase';
export { default as IconButton } from './IconButton';
export { default as IconCamera } from './IconCamera';
export { default as IconCampaign } from './IconCampaign';
export { default as IconCircle } from './IconCircle';
export { default as IconCloudUpload } from './IconCloudUpload';
export { default as IconCopy } from './IconCopy';
export { default as IconCrystalLamp } from './IconCrystalLamp';
export { default as IconDesign } from './IconDesign';
export { default as IconDiamond } from './IconDiamond';
export { default as IconDropdown } from './IconDropdown';
export { default as IconEmoji } from './IconEmoji';
export { default as IconFlag } from './IconFlag';
export { default as IconGuides } from './IconGuides';
export { default as IconLink } from './IconLink';
export { default as IconLocator } from './IconLocator';
export { default as IconMarker } from './IconMarker';
export { default as IconMessage } from './IconMessage';
export { default as IconPaperPlane } from './IconPaperPlane';
export { default as IconPersistentMenu } from './IconPersistentMenu';
export { default as IconSave } from './IconSave';
export { default as IconSend } from './IconSend';
export { default as IconSlinder } from './IconSlinder';
export { default as IconSquare } from './IconSquare';
export { default as IconSticker } from './IconSticker';
export { default as IconStore } from './IconStore';
export { default as IconToggle } from './IconToggle';
export { default as IconVideo } from './IconVideo';
